name: check-style

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'textos/**/estilo.yml'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate estilo.yml required fields
        shell: bash
        run: |
          set -euo pipefail
          shopt -s nullglob
          fail=0
          for f in textos/**/estilo.yml; do
            echo "Checking $f"
            grep -q '^voz:' "$f" || { echo "❌ missing 'voz' in $f"; fail=1; }
            grep -q '^ritmo:' "$f" || { echo "❌ missing 'ritmo' in $f"; fail=1; }
            grep -q '^metaforas:' "$f" || { echo "❌ missing 'metaforas' in $f"; fail=1; }
          done
          exit $fail
name: Validar metadados de estilo

on:
  pull_request:
    paths:
      - 'textos/**/estilo.yml'

jobs:
  validar_estilo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Checar campos obrigatórios em estilo.yml
        run: |
          for file in $(find textos -name "estilo.yml"); do
            echo "Verificando $file..."
            grep -q "voz:" "$file" || (echo "Falta campo 'voz:' em $file" && exit 1)
            grep -q "ritmo:" "$file" || (echo "Falta campo 'ritmo:' em $file" && exit 1)
            grep -q "metaforas:" "$file" || (echo "Falta campo 'metaforas:' em $file" && exit 1)
          done
