name: Update Navigation Links

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  update_nav:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug - List root directory
        run: ls -l

      - name: Debug - Print current working directory
        run: pwd

      - name: Debug - Check memotopia script permissions
        run: ls -l memotopia

      - name: Run memotopia update-nav
        run: |
          ./memotopia update-nav

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add textos/
          git diff --staged --quiet || git commit -m "chore(nav): atualiza links de navegação"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
