name: validate-structure

on:
  push:
    branches: [ main ]
    paths:
      - 'textos/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'textos/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate each text component structure
        shell: bash
        run: |
          set -euo pipefail
          shopt -s nullglob
          fail=0
          for d in textos/*/; do
            echo "Checking $d"
            [ -f "$d/index.md" ] || { echo "❌ missing index.md in $d"; fail=1; }
            [ -f "$d/estilo.yml" ] || { echo "❌ missing estilo.yml in $d"; fail=1; }
            [ -d "$d/insights" ] || { echo "❌ missing insights/ in $d"; fail=1; }
            [ -d "$d/referencias" ] || { echo "❌ missing referencias/ in $d"; fail=1; }
            # frontmatter must start with --- on first line
            if [ -f "$d/index.md" ]; then
              head -n1 "$d/index.md" | grep -q '^---$' || { echo "❌ $d/index.md must start with '---'"; fail=1; }
            fi
          done
          exit $fail
name: Validar estrutura de texto

on:
  pull_request:
    paths:
      - 'textos/**'
  push:
    branches: [main]
    paths:
      - 'textos/**'

jobs:
  validar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Verificar pastas obrigatórias e frontmatter
        shell: bash
        run: |
          set -euo pipefail
          shopt -s nullglob
          for dir in textos/*/ ; do
            echo "▶ Checando $dir"
            test -f "${dir}index.md" || { echo "Falta index.md em ${dir}"; exit 1; }
            test -d "${dir}insights"  || { echo "Falta pasta /insights em ${dir}"; exit 1; }
            test -d "${dir}referencias" || { echo "Falta pasta /referencias em ${dir}"; exit 1; }
            # frontmatter YAML mínima no index.md (--- na 1ª linha)
            head -n 1 "${dir}index.md" | grep -q '^---$' || { echo "index.md sem frontmatter YAML em ${dir}"; exit 1; }
          done
          echo "✓ Estrutura válida"
